---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml

driver:
  name: podman

platforms:
  - name: "rockylinux9"
    image: docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-rockylinux9}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    kubernetes_namespace: ${KUBERNETES_NAMESPACE:-molecule-testing}
    become_method: su
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  log: true
  playbooks:
    create: utils/${MOLECULE_DRIVER_NAME}/create.yml
    destroy: utils/${MOLECULE_DRIVER_NAME}/destroy.yml
    converge: converge.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        ansible_connection: containers.podman.podman

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"
    ANSIBLE_STDOUT_CALLBACK: yaml

  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --force-handlers


scenario:
  name: webserver
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
