---
- name: Converge
  hosts: all
  gather_facts: true
  connection: kubernetes.core.kubectl
  # vars:
  #   ansible_kubectl_namespace: "asdf"
  tasks:

    - name: Print release via shell
      ansible.builtin.command:
        cmd: cat /etc/redhat-release
      changed_when: false
      register: redhat_release

    - name: Print hostname via shell
      ansible.builtin.command:
        cmd: cat /etc/hostname
      changed_when: false
      register: hostname

    - name: Print release results
      ansible.builtin.debug:
        var: redhat_release

    - name: Print hostname results
      ansible.builtin.debug:
        var: hostname

    # - name: "Wait for PostgreSQL to be ready"
    #   ansible.builtin.wait_for:
    #     host: "{{ ansible_host }}"
    #     port: 5432
    #     delay: 10  # Time to wait before first check
    #     timeout: 120 # Total time to wait before failing
    #   delegate_to: localhost

    # - name: "Include the database role"
    #   ansible.builtin.include_role:
    #     name: "myorg.custom_collection.database"
...
