---
- name: Converge
  hosts: runner
  gather_facts: false
  tasks:

    - name: Install pip dependencies
      ansible.builtin.pip:
        name: "psycopg2-binary"
        state: present

    - name: "Wait for PostgreSQL to be ready"
      ansible.builtin.wait_for:
        host: "{{ db_host }}"
        port: 5432
        delay: 1  # Time to wait before first check
        timeout: 120 # Total time to wait before failing
      loop: "{{ groups['database'] }}"
      loop_control:
        loop_var: db_host

    - name: "Include the database role for each database host"
      ansible.builtin.include_role:
        name: "myorg.custom_collection.database"
      loop: "{{ groups['database'] }}"
      loop_control:
        loop_var: db_host
      vars:
        database_host: "{{ hostvars[db_host]['inventory_hostname'] }}"
        database_server_name: "webapp_prod"
        database_server_user: "webapp_user"
        database_server_password: "SecurePassword123"
        database_server_user_password: "SecurePassword123"
...