---
- name: Converge
  hosts: all
  gather_facts: true
  connection: community.okd.oc
  tasks:
    - name: "Wait for PostgreSQL to be ready"
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 5432
        delay: 10  # Time to wait before first check
        timeout: 120 # Total time to wait before failing
      delegate_to: localhost

    - name: "Include the db_server role"
      ansible.builtin.include_role:
        name: "myorg.custom_collection.database"
...