---
dependency:
  name: galaxy
  options:
    requirements-file: collections/requirements.yml
driver:
  name: default
  options:
    managed: true
    ansible_connection_options:
      connection: local
platforms:
  - name: molecule-ubi8-python-1
    image: registry.access.redhat.com/ubi8/python-39@sha256:301fec66443f80c3cc507ccaf72319052db5a1dc56deb55c8f169011d4bbaacb
    namespace: ${MOLECULE_NAMESPACE:-ci-rh1-custom-collection}
    workingDir: '/tmp'
  - name: molecule-ubi8-python-2
    image: registry.access.redhat.com/ubi8/python-39@sha256:301fec66443f80c3cc507ccaf72319052db5a1dc56deb55c8f169011d4bbaacb
    namespace: ${MOLECULE_NAMESPACE:-ci-rh1-custom-collection}
    workingDir: '/tmp'
provisioner:
  name: ansible
  # Failing to write the ansible into /.ansible/tmp
  playbooks:
    converge: converge.yml
    create: ../utils/kubernetes-pod/playbooks/create.yml
    destroy: ../utils/kubernetes-pod/playbooks/destroy.yml
    prepare: ../utils/kubernetes-pod/playbooks/prepare.yml
    verify: verify.yml
  config_options:
    defaults:
      remote_tmp: '/tmp'
      # This just says go back a directory and thats your roles path
      # You can also provide this via pipeline with something like this
      # ANSIBLE_ROLES_PATH: $COLLECTION_ROLES

      # COLLECTIONS_PATH: ${PROJECT_SOURCE}
      # ANSIBLE_ROLES_PATH: ${PROJECT_SOURCE}/${backup_file_molecule_namespace}
  inventory:
    group_vars:
      all:
        backup_file_molecule_namespace: ${DEVWORKSPACE_NAMESPACE}
        backup_file_molecule_pip_dependencies:
          - kubernetes
verifier:
  name: ansible
scenario:
  name: database
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - verify
...
