---
dependency:
  name: galaxy
  options:
    requirements-file: ../provisioners/${PROVISIONER:-podman}/requirements.yml
driver:
  name: default
  options:
    managed: true
    ansible_connection_options:
      connection: local
platforms:
  - name: molecule-ubi8-python-1
    image: registry.access.redhat.com/ubi8/python-39@sha256:301fec66443f80c3cc507ccaf72319052db5a1dc56deb55c8f169011d4bbaacb
    namespace: ${MOLECULE_NAMESPACE:-ci-rh1-custom-collection}
    workingDir: '/tmp'
  - name: molecule-ubi8-python-2
    image: registry.access.redhat.com/ubi8/python-39@sha256:301fec66443f80c3cc507ccaf72319052db5a1dc56deb55c8f169011d4bbaacb
    namespace: ${MOLECULE_NAMESPACE:-ci-rh1-custom-collection}
    workingDir: '/tmp'
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
    create: ../provisioners/${PROVISIONER:-podman}/create.yml
    destroy: ../provisioners/${PROVISIONER:-podman}/destroy.yml
    # prepare: ../provisioners/${PROVISIONER:-podman}/prepare.yml
    # prepare: ../utils/kubernetes-pod/playbooks/prepare.yml
    verify: verify.yml
  inventory:
    links:
      group_vars: ../provisioners/${PROVISIONER:-podman}/group_vars/
verifier:
  name: ansible
scenario:
  name: database
  test_sequence:
    - dependency
    - syntax
    - create
    - converge
    - verify
...
