apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ansible-galaxy-collection-release
  annotations:
    pipelinesascode.tekton.dev/task-1: "[git-clone]"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/david-igou/tekton-ansible/refs/heads/main/task/ansible-galaxy-collection-build/ansible-galaxy-collection-build.yml"
    pipelinesascode.tekton.dev/task-3: "https://raw.githubusercontent.com/david-igou/tekton-ansible/refs/heads/main/task/ansible-molecule/molecule-task.yml"
    pipelinesascode.tekton.dev/task-4: "https://raw.githubusercontent.com/david-igou/tekton-ansible/refs/heads/main/task/ansible-galaxy-collection-publish/ansible-galaxy-collection-publish.yml"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/tags/*]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  workspaces:
  - name: galaxy-credentials
    secret:
      secretName: galaxy-credentials
  - name: aap-credentials
    secret:
      secretName: aap-credentials
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineSpec:
    workspaces:
    - name: shared-workspace
    tasks:
      - name: fetch-source
        taskRef:
          name: git-clone
        params:
        - name: url
          value: "{{ repo_url }}"
        - name: revision
          value: "{{ revision }}"
        - name: verbose
          value: "true"
        workspaces:
        - name: output
          workspace: shared-workspace

      - name: ansible-galaxy-collection-build
        runAfter:
        - fetch-source
        taskRef:
          name: ansible-galaxy-collection-build
        workspaces:
        - name: source
          workspace: shared-workspace

      - name: molecule
        runAfter:
        - ansible-galaxy-collection-build
        taskRef:
          name: molecule
        workspaces:
        - name: source
          workspace: shared-workspace
        params:
        - name: collection-bundle
          value: $(tasks.ansible-galaxy-collection-build.results.collection-bundle)
        - name: molecule-scenario
          value: "magic"

      - name: ansible-galaxy-collection-publish
        runAfter:
        - molecule
        taskRef:
          name: ansible-galaxy-collection-publish
        params:
        - name: COLLECTION_BUNDLE
          value: $(tasks.ansible-galaxy-collection-build.results.collection-bundle)
        workspaces:
        - name: source
          workspace: shared-workspace
        - name: galaxy-credentials
          workspace: galaxy-credentials

      - name: approve-collection-release
        runAfter:
        - ansible-galaxy-collection-publish
        workspaces:
        - name: shared-workspace
          workspace: shared-workspace
        - name: aap-credentials
          workspace: aap-credentials
        params:
        - name: url
          value: "http://aap-dev.aap-dev.svc.cluster.local"
        - name: namespace
          value: "myorg"
        - name: collection-name
          value: "custom_collection"
        - name: collection-version
          value: "{{ git_tag }}"
        taskSpec:
          workspaces:
          - name: shared-workspace
          - name: aap-credentials
          steps:
          - name: approve-collection-release
            image: registry.redhat.io/openshift4/ose-tools-rhel9 #todo find upstream image
            script: |
              #!/usr/bin/env sh
              set -eux -o

              # 1. Set your variables
              AAP_URL="$(cat "$(params.url)")"
              NAMESPACE="$(params.namespace)"
              NAME="$(params.collection-name)"
              VERSION="$(params.collection-version)"
              PASSWORD="$(cat "$(workspaces.aap-credentials.path)/password")"

              # Login and get API Token
              AAP_TOKEN=$(curl -sk -u admin:$PASSWORD -X POST $AAP_URL/api/gateway/v1/tokens/ | jq -r .token)

              # 2. Construct the URL
              # Note: Ensure you include the trailing slash if your Hub requires it
              URL="$AAP_URL/api/galaxy/v3/collections/$NAMESPACE/$NAME/versions/$VERSION/move/staging/published/"

              # 3. The Approval Call (You may need to loop this if you get a 404 initially)
              curl -k -X POST -H "Authorization: Bearer $AAP_TOKEN" -H "Content-Type: application/json" $URL