apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ansible-galaxy-collection-release
  annotations:
    pipelinesascode.tekton.dev/task-1: "[git-clone]"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/david-igou/tekton-ansible/refs/heads/main/task/ansible-galaxy-collection-build/ansible-galaxy-collection-build.yml"
    pipelinesascode.tekton.dev/task-3: "https://raw.githubusercontent.com/david-igou/tekton-ansible/refs/heads/main/task/ansible-molecule/molecule-task.yml"
    pipelinesascode.tekton.dev/task-4: "https://raw.githubusercontent.com/david-igou/tekton-ansible/refs/heads/main/task/ansible-galaxy-collection-publish/ansible-galaxy-collection-publish.yml"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/tags/1.*]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  workspaces:
  - name: galaxy-credentials
    secret:
      secretName: automationhub-credentials
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  pipelineSpec:
    workspaces:
    - name: shared-workspace
    tasks:
      - name: fetch-source
        taskRef:
          name: git-clone
        params:
        - name: url
          value: "{{ repo_url }}"
        - name: revision
          value: "{{ revision }}"
        - name: verbose
          value: "true"
        workspaces:
        - name: output
          workspace: shared-workspace

      - name: ansible-galaxy-collection-build
        runAfter:
        - fetch-source
        taskRef:
          name: ansible-galaxy-collection-build
        workspaces:
        - name: source
          workspace: shared-workspace

      - name: molecule
        runAfter:
        - ansible-galaxy-collection-build
        taskRef:
          name: molecule
        workspaces:
        - name: source
          workspace: shared-workspace
        params:
        - name: collection-bundle
          value: $(tasks.ansible-galaxy-collection-build.results.collection-bundle)
        - name: molecule-scenario
          value: "magic"

      - name: ansible-galaxy-collection-publish
        runAfter:
        - fetch-source
        taskRef:
          name: ansible-galaxy-collection-publish
        params:
        - name: COLLECTION_BUNDLE
          value: $(tasks.ansible-galaxy-collection-build.results.collection-bundle)
        workspaces:
        - name: source
          workspace: shared-workspace
        - name: galaxy-credentials
          workspace: galaxy-credentials